services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oraclexe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: app
      APP_USER_PASSWORD: app
      ORACLE_DATABASE: XEPDB1
    volumes:
      - ./db/init:/container-entrypoint-initdb.d:ro
      - oracle_data:/opt/oracle/oradata

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_USER: app
      DB_PASSWORD: app
      DB_CONNECT_STRING: host.docker.internal:1521/XEPDB1   # ← usa el puerto del host (como DBeaver)
    extra_hosts:
      - "host.docker.internal:host-gateway"                 # ← habilita ese hostname en Linux
    ports:
      - "3000:3000"
    depends_on:
      - oracle
        
    restart: unless-stopped

volumes:
  oracle_data:
