DROP TABLE CENTRO CASCADE CONSTRAINTS;
CREATE TABLE CENTRO (
  ID_CENTRO NUMBER(38,0),
  NOMBRE    VARCHAR2(40)
);

DROP TABLE CORRELATIVO CASCADE CONSTRAINTS;
CREATE TABLE CORRELATIVO (
  ID_CORRELATIVO NUMBER(38,0),
  FECHA          DATE,
  NO_EXAMEN      NUMBER(38,0)
);

DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;
CREATE TABLE DEPARTAMENTO (
  ID_DEPARTAMENTO NUMBER(38,0),
  NOMBRE          VARCHAR2(26),
  CODIGO          NUMBER(38,0)
);

DROP TABLE ESCUELA CASCADE CONSTRAINTS;
CREATE TABLE ESCUELA (
  ID_ESCUELA NUMBER(38,0),
  NOMBRE     VARCHAR2(40),
  DIRECCION  VARCHAR2(40),
  ACUERDO    VARCHAR2(40)
);

DROP TABLE EXAMEN CASCADE CONSTRAINTS;
CREATE TABLE EXAMEN (
  ID_EXAMEN                          NUMBER(38,0),
  REGISTRO_ID_ESCUELA                NUMBER(38,0),
  REGISTRO_ID_CENTRO                 NUMBER(38,0),
  REGISTRO_MUNICIPIO_ID              NUMBER(38,0),
  REGISTRO_MUNICIPIO_DEPARTAMENTO_ID NUMBER(38,0),
  REGISTRO_ID                        NUMBER(38,0),
  CORRELATIVO_ID                     NUMBER(38,0)
);

DROP TABLE MUNICIPIO CASCADE CONSTRAINTS;
CREATE TABLE MUNICIPIO (
  ID_MUNICIPIO    NUMBER(38,0),
  DEPARTAMENTO_ID NUMBER(38,0),
  NOMBRE          VARCHAR2(128),
  CODIGO          NUMBER(38,0)
);

DROP TABLE PREGUNTAS CASCADE CONSTRAINTS;
CREATE TABLE PREGUNTAS (
  ID             NUMBER(38,0),
  PREGUNTA_TEXTO VARCHAR2(256),
  RESPUESTA      NUMBER(38,0),
  RES1           VARCHAR2(128),
  RES2           VARCHAR2(128),
  RES3           VARCHAR2(128),
  RES4           VARCHAR2(128)
);

DROP TABLE PREGUNTAS_PRACTICO CASCADE CONSTRAINTS;
CREATE TABLE PREGUNTAS_PRACTICO (
  ID_PREGUNTA_PRACTICO NUMBER(38,0),
  PREGUNTA_TEXTO       VARCHAR2(128),
  PUNTEO               NUMBER(38,0)
);

DROP TABLE REGISTRO CASCADE CONSTRAINTS;
CREATE TABLE REGISTRO (
  ID_REGISTRO               NUMBER(38,0),
  UBICACION_ESCUELA_ID      NUMBER(38,0),
  UBICACION_CENTRO_ID       NUMBER(38,0),
  MUNICIPIO_ID              NUMBER(38,0),
  MUNICIPIO_DEPARTAMENTO_ID NUMBER(38,0),
  FECHA                     DATE,
  TIPO_TRAMITE              VARCHAR2(40),
  TIPO_LICENCIA             VARCHAR2(40),
  NOMBRE_COMPLETO           VARCHAR2(40),
  GENERO                    VARCHAR2(40)
);

DROP TABLE RESPUESTA_PRACTICO_USUARIO CASCADE CONSTRAINTS;
CREATE TABLE RESPUESTA_PRACTICO_USUARIO (
  ID_RESPUESTA_PRACTICO NUMBER(38,0),
  PREGUNTA_PRACTICO_ID  NUMBER(38,0),
  EXAMEN_ID             NUMBER(38,0),
  NOTA                  NUMBER(38,0)
);

DROP TABLE RESPUESTA_USUARIO CASCADE CONSTRAINTS;
CREATE TABLE RESPUESTA_USUARIO (
  ID_RESPUESTA_USUARIO NUMBER(38,0),
  PREGUNTA_ID          NUMBER(38,0),
  EXAMEN_ID            NUMBER(38,0),
  RESPUESTA            NUMBER(38,0)
);

DROP TABLE UBICACION CASCADE CONSTRAINTS;
CREATE TABLE UBICACION (
  ESCUELA_ID NUMBER(38,0),
  CENTRO_ID  NUMBER(38,0)
);

